### ISSUE TITLE
经过使用我发现在centos debian 等 vps 中内存占用很高。

### ISSUE THREAD

**Issue by ergatea** [dndx/shadowsocks-libuv#11]

**Comment by dndx** [comment]
麻烦贴一下 ps 输出及简单的现象描述，否则无法帮你定位问题。

**Comment by ihipop** [comment]
内存倒是没发现 就是运行了一会 CPU会变成102% 关键是我连着的时候他不102%的 但是断开SSH一段时间上去看 CPU满了。。现在用回node-js版本的了 暂时很稳定

**Comment by ergatea** [comment]
今天看的code眼睛累，布置在 raspberry pi 的local libev  和布置在 openvz上的 server libev 工作的很正常：

raspberry pi 的 local libev
root      1652  0.1  0.2   4348  1220 ?        Ss   20:03   0:08 /usr/local/bin/shadowsocks
openvz 上的 server libev 
root      1775  0.0  0.2   4236  1312 ?        S    Jan08   0:14 /usr/local/bin/shadowsocks

**Comment by dndx** [comment]
This is a known issue and I'm working for a solution.

**Comment by ihipop** [comment]
内存占用确实还可以。但是就是跑了一段时间以后就102%的CPU. 而且不总是出现。我开了server以后开着SSH远程看了很久 CPU都不高。下个班回家以后再看 VPS已经在CPU的102%处呻吟了

**Comment by dndx** [comment]
I am currently working to rewrite connection close logic and hopefully it
will fix the problem. Please use shadowsocks-nodejs for a temporary
solution and I will fix it ASAP.

2013/1/10 ihipop notifications@github.com

> 内存占用确实还可以。但是就是跑了一段时间以后就102%的CPU. 而且不总是出现。我开了server以后开着SSH远程看了很久
> CPU都不高。下个班回家以后再看 VPS已经在CPU的102%处呻吟了
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dndx/shadowsocks-libuv/issues/11#issuecomment-12082267.

## 

---

Datong

**Comment by dndx** [comment]
Will this cause the delay of request process?

You mean version of shadowsocks-libuv on Jan 8?

On Tue, Jan 15, 2013 at 7:54 PM, arowser notifications@github.com wrote:

> I think the CPU 100% reason is that the nanosleep delay too short, its in
> libuv/src/unix/stream.c line 552, and change it from:
> struct timespec timeout = { 0, 1 };
> 
> nanosleep(&timeout, NULL);
> to:
> struct timespec timeout = { 0, 5000000L };
> 
> nanosleep(&timeout, NULL);
> 
> Its work for me, not happened after run several days.
> 
> And its seems the version that Jan 8 faster than after version, do you
> know the reasons?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dndx/shadowsocks-libuv/issues/11#issuecomment-12300277.

## 

---

Datong
