### ISSUE TITLE
make后编译出错

### ISSUE THREAD

**Issue by opalhair** [dndx/shadowsocks-libuv#16]
错误如下：
cc -Wall -O2 -DNDEBUG -I libuv/include -std=gnu99 -o \
        server server.c utils.c encrypt.c md5.c rc4.c \
        libuv/libuv.a -lpthread -lcrypto -lm -lrt
server.c: In function  after_write_cb :
server.c:151: warning: dereferencing type-punned pointer will break strict-aliasing rules

**Comment by hanai** [comment]
试试加上 -Wno-strict-aliasing

**Comment by opalhair** [comment]
请问加在哪里？

**Comment by hanai** [comment]
奇怪，我编译的时候 server.c 没问题，md5.c 出这个警告了。

**Comment by dndx** [comment]
奇怪，看了半天 `server.c` 的 151 行 也不在 `after_write_cb` 函数里。

**Comment by opalhair** [comment]
就是不知道怎么回事，之前是因为 CPU 占用太高，所以重新 git 个新版本就出事，旧版本又被我删掉了，请问有什么办法可以下载半个月前的版本？谢谢！

**Comment by dndx** [comment]
奇怪了，请 checkout 最新代码，看看还出错不。

Travis Clang 和 GCC 编译都是通过的。

**Comment by opalhair** [comment]
新代码昨天也试了，结果一样，不知道是不是之前 update 到 CentOS 5.9 的关系，还有我没改 config-unix.mk ，make 之后就出来 cc -Wall -O2 -DNDEBUG -I libuv/include -std=gnu99 -o \，不知道甚么原因？

**Comment by dndx** [comment]
能否用最新代码编译一次把 warning 贴到这里？

**Comment by opalhair** [comment]
跟之前一样："cc -Wall -O2 -DNDEBUG -I libuv/include -std=gnu99 -o \
        server server.c utils.c encrypt.c md5.c rc4.c \
        libuv/libuv.a -lpthread -lcrypto -lm -lrt
server.c: In function ‘after_write_cb’:
server.c:151: warning: dereferencing type-punned pointer will break strict-aliasing rules"
